server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        use_sql_comments: false
        format_sql: true

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
